db: sqlite
dbConfig:
  host: localhost
  user: root
  password: my-secret-pw
  dbName: test
workerFetchInterval: 5s
images:
  - name: cgr.dev/chainguard/nginx
    constraint: "^1.2.*"
    mainPackage: nginx
